import { Trash2 } from 'lucide-react';

export interface LibraryDeleteTarget { type: 'lesson' | 'folder'; id: string; title: string; folderId?: string; }
interface LibraryDeleteDialogProps { target: LibraryDeleteTarget | null; onCancel: () => void; onDeleteLesson: (target: LibraryDeleteTarget) => void; onDeleteFolder: (target: LibraryDeleteTarget, keepLessons: boolean) => void; }

export function LibraryDeleteDialog({ target, onCancel, onDeleteLesson, onDeleteFolder }: LibraryDeleteDialogProps) {
  if (!target) return null;
  const isFolder = target.type === 'folder';
  return <div id="delete-confirm-modal" className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-xs animate-fadeIn"><div className="bg-white rounded-2xl max-w-sm w-full p-5 shadow-xl border border-slate-150 animate-scaleUp text-left">
    <div className="flex items-start gap-3"><div className="p-2.5 bg-rose-50 text-rose-600 rounded-xl shrink-0"><Trash2 className="w-5 h-5" /></div><div className="flex-1 min-w-0"><h4 className="text-xs font-extrabold text-slate-900">{isFolder ? 'Xác nhận xóa thư mục?' : 'Xác nhận xóa bài học?'}</h4><div className="text-[11px] text-slate-500 mt-2 leading-relaxed">{isFolder ? <>Bạn đang xóa thư mục <strong className="text-slate-850">"{target.title}"</strong>. Hãy chọn cách xử lý các bài học bên trong:</> : <>Bạn có chắc muốn xóa vĩnh viễn bài giảng <strong className="text-slate-850">"{target.title}"</strong>? Hành động này không thể hoàn tác.</>}</div></div></div>
    <div className="mt-5 flex flex-col gap-2 justify-end">{isFolder ? <div className="space-y-1.5 w-full"><button type="button" id="confirm-delete-folder-keep-lessons-btn" onClick={() => onDeleteFolder(target, true)} className="w-full px-3 py-1.5 bg-slate-100 hover:bg-indigo-50 hover:text-indigo-650 text-slate-700 rounded-lg text-[10px] font-bold cursor-pointer text-center border border-transparent transition">Xóa thư mục, giữ bài học trong Chưa phân loại</button><button type="button" id="confirm-delete-folder-all-btn" onClick={() => onDeleteFolder(target, false)} className="w-full px-3 py-1.5 bg-rose-600 hover:bg-rose-700 text-white rounded-lg text-[10px] font-bold cursor-pointer text-center transition">Xóa thư mục và toàn bộ bài học</button><button type="button" id="cancel-delete-folder-btn" onClick={onCancel} className="w-full px-3 py-1.5 bg-white hover:bg-slate-50 border border-slate-200 text-slate-500 rounded-lg text-[10px] font-bold cursor-pointer text-center transition">Hủy bỏ</button></div> : <div className="flex items-center justify-end gap-2"><button type="button" id="cancel-delete-lesson-btn" onClick={onCancel} className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-650 rounded-lg text-[10px] font-bold cursor-pointer text-center transition">Hủy bỏ</button><button type="button" id="confirm-delete-lesson-btn" onClick={() => onDeleteLesson(target)} className="px-3 py-1.5 bg-rose-600 hover:bg-rose-700 text-white rounded-lg text-[10px] font-bold cursor-pointer text-center transition">Xóa vĩnh viễn</button></div>}</div>
  </div></div>;
}
