import type { Dispatch, SetStateAction } from 'react';
import type { LessonSettings, SpeechItem } from '../../types';
import { buildLessonDraft } from '../../domain/lessonModel';
import type { SavedFolder, SavedLesson } from '../../features/lessons/localLibraryRepository';

type Flash = (message: string, type: 'success' | 'error' | 'info') => void;
interface Input { folders: SavedFolder[]; uncategorizedLessons: SavedLesson[]; newFolderName: string; editingFolderId: string | null; editingFolderName: string; newLessonTitle: string; editingLessonId: string | null; editingLessonTitle: string; targetFolderId: string; currentRawText: string; currentSpeechList: SpeechItem[]; currentSettings: LessonSettings; save: (folders: SavedFolder[], uncategorized: SavedLesson[]) => void; flash: Flash; onLoadLesson: (lesson: SavedLesson) => void; setNewFolderName: (value:string)=>void; setShowNewFolderInput:(value:boolean)=>void; setEditingFolderId:(value:string|null)=>void; setEditingFolderName:(value:string)=>void; setNewLessonTitle:(value:string)=>void; setShowSaveLessonForm:(value:boolean)=>void; setEditingLessonId:(value:string|null)=>void; setEditingLessonTitle:(value:string)=>void; setExpandedFolders: Dispatch<SetStateAction<Record<string,boolean>>>; }
export function createLocalLibraryActions(input: Input) {
  const saveLesson = () => { const title=input.newLessonTitle.trim(); if(!title){input.flash('Vui lòng nhập tiêu đề cho bài giảng','error');return;} if(!input.currentRawText.trim()){input.flash('Nội dung bài học trống, không thể lưu!','error');return;} const now=Date.now(); const lesson:SavedLesson={schemaVersion:1,revision:1,id:`lesson-${now}-${Math.random().toString(36).slice(2,7)}`,...buildLessonDraft({title,rawText:input.currentRawText,speechList:input.currentSpeechList,settings:input.currentSettings,folderId:input.targetFolderId==='unassigned'?null:input.targetFolderId}),createdAt:now,updatedAt:now}; if(input.targetFolderId==='unassigned') input.save(input.folders,[lesson,...input.uncategorizedLessons]); else { input.save(input.folders.map(folder=>folder.id===input.targetFolderId?{...folder,lessons:[lesson,...folder.lessons]}:folder),input.uncategorizedLessons); input.setExpandedFolders(current=>({...current,[input.targetFolderId]:true})); } input.setNewLessonTitle('');input.setShowSaveLessonForm(false);input.flash(`Đã lưu "${title}" thành công.`,'success'); };
  return {
    createFolder:()=>{const name=input.newFolderName.trim();if(!name)return;input.save([...input.folders,{id:`folder-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name,lessons:[],createdAt:Date.now()}],input.uncategorizedLessons);input.setNewFolderName('');input.setShowNewFolderInput(false);input.flash(`Đã tạo thư mục "${name}"`,'success');},
    deleteFolder:(id:string,keep:boolean)=>{const folder=input.folders.find(value=>value.id===id);if(!folder)return;input.save(input.folders.filter(value=>value.id!==id),keep?[...input.uncategorizedLessons,...folder.lessons]:input.uncategorizedLessons);input.flash(keep?'Đã xóa thư mục và giữ lại bài học.':'Đã xóa thư mục cùng bài học.','info');},
    startRenameFolder:(id:string,name:string)=>{input.setEditingFolderId(id);input.setEditingFolderName(name);},
    saveRenameFolder:()=>{const name=input.editingFolderName.trim();if(!name||!input.editingFolderId)return;input.save(input.folders.map(folder=>folder.id===input.editingFolderId?{...folder,name}:folder),input.uncategorizedLessons);input.setEditingFolderId(null);input.flash('Đã đổi tên thư mục.','success');},
    saveLesson,
    loadLesson:(lesson:SavedLesson)=>{input.onLoadLesson(lesson);input.flash(`Đã khôi phục bài học "${lesson.title}".`,'success');document.getElementById('words-maker-box')?.scrollIntoView({behavior:'smooth',block:'start'});},
    deleteLesson:(id:string,folderId?:string)=>{if(folderId)input.save(input.folders.map(folder=>folder.id===folderId?{...folder,lessons:folder.lessons.filter(lesson=>lesson.id!==id)}:folder),input.uncategorizedLessons);else input.save(input.folders,input.uncategorizedLessons.filter(lesson=>lesson.id!==id));input.flash('Đã xóa bài học khỏi thư viện.','info');},
    startRenameLesson:(id:string,title:string)=>{input.setEditingLessonId(id);input.setEditingLessonTitle(title);},
    saveRenameLesson:(folderId?:string)=>{const title=input.editingLessonTitle.trim();if(!title||!input.editingLessonId)return;const folders=folderId?input.folders.map(folder=>folder.id===folderId?{...folder,lessons:folder.lessons.map(lesson=>lesson.id===input.editingLessonId?{...lesson,title}:lesson)}:folder):input.folders;const uncategorized=folderId?input.uncategorizedLessons:input.uncategorizedLessons.map(lesson=>lesson.id===input.editingLessonId?{...lesson,title}:lesson);input.save(folders,uncategorized);input.setEditingLessonId(null);input.flash('Đã đổi tên bài học.','success');},
  };
}
