import React from 'react';
import { AlertTriangle, Loader2, Mic } from 'lucide-react';
interface AudioExportProgressProps { status: 'processing' | 'recording'; progressText: string; progressPercent: number; soundLevel: number; micActiveWarning: boolean; logs: string[]; onCancel: () => void; }
export function AudioExportProgress({ status, progressText, progressPercent, soundLevel, micActiveWarning, logs, onCancel }: AudioExportProgressProps) {
  return <div className="space-y-5 py-2">
    <div className="text-center space-y-2"><Loader2 className="w-9 h-9 text-indigo-600 animate-spin mx-auto" /><h4 className="font-bold text-sm text-slate-800">{status === 'recording' ? 'Đang thu âm trực tiếp...' : 'Đang tổng hợp âm thanh...'}</h4><p className="text-xs text-slate-500 font-medium">{progressText}</p></div>
    <div className="space-y-1"><div className="flex justify-between text-[11px] font-bold text-slate-400"><span>TIẾN ĐỘ TỔNG HỢP</span><span>{progressPercent}%</span></div><div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden"><div className="bg-indigo-600 h-full transition-all duration-300" style={{ width: `${progressPercent}%` }} /></div></div>
    {status === 'recording' && <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-3.5"><div className="flex justify-between items-center"><span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5"><Mic className={`w-3.5 h-3.5 ${soundLevel > 2 ? 'text-emerald-500 animate-pulse' : 'text-slate-400'}`} />Tín hiệu thu âm từ thẻ:</span><span className="text-xs font-bold text-slate-650">{soundLevel > 2 ? 'Đang phát & thu âm...' : 'Đang chờ phát (hoặc im lặng)...'}</span></div><div className="w-full bg-slate-250 rounded-full h-4 overflow-hidden flex gap-[2px] p-[2px]"><div className="bg-emerald-500 h-full rounded-r-xs transition-all duration-75" style={{ width: `${Math.min(100, Math.max(5, soundLevel * 2.5))}%` }} /></div>{micActiveWarning && <div className="p-4 bg-rose-50 border border-rose-200 rounded-xl text-[11px] text-rose-800 leading-relaxed space-y-2.5 animate-pulse"><div className="flex gap-2 items-start font-extrabold text-rose-900 text-xs"><AlertTriangle className="w-4.5 h-4.5 shrink-0 text-rose-600 animate-bounce" /><span>CHƯA NHẬN ĐƯỢC TÍN HIỆU ÂM THANH!</span></div><p className="text-[10.5px]">Google Chrome không đẩy tiếng nói speechSynthesis vào luồng thu âm của một thẻ riêng biệt (Tab). Vui lòng khắc phục bằng cách chọn Entire Screen và bật chia sẻ âm thanh hệ thống, hoặc chuyển sang Premium AI.</p></div>}</div>}
    <div className="space-y-1.5"><span className="text-[10px] font-extrabold text-slate-400 tracking-wider uppercase block">Nhật ký xử lý:</span><div className="bg-slate-900 rounded-xl p-3.5 h-32 overflow-y-auto font-mono text-[10px] text-indigo-200 space-y-1 select-text scrollbar-thin">{logs.slice().reverse().map((log, index) => <div key={`${index}-${log}`} className="leading-relaxed opacity-90">{log}</div>)}</div></div>
    <button type="button" onClick={onCancel} className="w-full bg-slate-100 text-slate-700 hover:bg-slate-200 rounded-xl py-2 font-bold text-xs transition active:scale-98 cursor-pointer">Hủy bỏ quy trình</button>
  </div>;
}
